#!/usr/bin/python3
#Sends a request to poll device data

import requests
import config

token = config.WF_TOKEN
device = config.WF_DEVICE_ID
station = config.WF_STATION_ID

print("Getting Device Data...")
URL = "https://swd.weatherflow.com/swd/rest/observations/device/{}/?token={}".format(device, token)
r = requests.get(url = URL)
d = r.json()
print("Response:")
print(str(d) + "\n")

print("Formatted:")
print("Status Code: " + str(d['status']['status_code']))
print("Status Message: " + str(d['status']['status_message']))
print("Device ID: " + str(d['device_id']))
print("Type: " + str(d['type']))
print("Source: " + str(d['source']))
print("Pressure Trend: " + str(d['summary']['pressure_trend']))
print("Strike Count 1H: " + str(d['summary']['strike_count_1h']))
print("Strike Count 3H: " + str(d['summary']['strike_count_3h']))
print("Precip Total 1H: " + str(d['summary']['precip_total_1h']))
print("Strike Last Dist: " + str(d['summary']['strike_last_dist']))
print("Strike Last Epoch: " + str(d['summary']['strike_last_epoch']))
print("Precip Accum Local Yesterday: " + str(d['summary']['precip_accum_local_yesterday']))
print("Precip Accum Local Yesterday Final: " + str(d['summary']['precip_accum_local_yesterday_final']))
print("Precip Analysis Type Yesterday: " + str(d['summary']['precip_analysis_type_yesterday']))
print("Feels Like: " + str(d['summary']['feels_like']))
print("Heat Index: " + str(d['summary']['heat_index']))
print("Wind Chill: " + str(d['summary']['wind_chill']))
print("Epoch: " + str(d['obs'][0][0]))
print("Wind Lull: " + str(d['obs'][0][1]))
print("Wind Avg: " + str(d['obs'][0][2]))
print("Wind Gust: " + str(d['obs'][0][3]))
print("Wind Direction: " + str(d['obs'][0][4]))
print("Wind Sample Interval: " + str(d['obs'][0][5]))
print("Pressure: " + str(d['obs'][0][6]))
print("Air Temperature: " + str(d['obs'][0][7]))
print("Relative Humidity: " + str(d['obs'][0][8]))
print("Illuminance: " + str(d['obs'][0][9]))
print("UV: " + str(d['obs'][0][10]))
print("Solar Radiation: " + str(d['obs'][0][11]))
print("Rain Accumulation: " + str(d['obs'][0][12]))
print("Precipitation Type: " + str(d['obs'][0][13]))
print("Average Strike Distance: " + str(d['obs'][0][14]))
print("Strike Count: " + str(d['obs'][0][15]))
print("Battery: " + str(d['obs'][0][16]))
print("Report Interval: " + str(d['obs'][0][17]))
print("Local Day Rain Accumulation: " + str(d['obs'][0][18]))
print("NC Rain Accumulation: " + str(d['obs'][0][19]))
print("Local Day NC Rain Accumulation: " + str(d['obs'][0][20]))
print("Precipitation Analysis Type: " + str(d['obs'][0][21]))
print("\n")
print("Getting Station Data...")
URL = "https://swd.weatherflow.com/swd/rest/observations/station/{}?token={}".format(station, token)
print(URL)
r = requests.get(url = URL)
d = r.json()
print("Response:")
print(str(d) + "\n")
print("Elevation: " + str(d['elevation']))
print("Is Public: " + str(d['is_public']))
print("Latitude: " + str(d['latitude']))
print("Longitude: " + str(d['longitude']))
print("Air Density: " + str(d['obs'][0]['air_density'])) 
print("Air Temperature: " + str(d['obs'][0]['air_temperature'])) 
print("Barometric Pressure: " + str(d['obs'][0]['barometric_pressure'])) 
print("Brightness: " + str(d['obs'][0]['brightness'])) 
print("Delta T: " + str(d['obs'][0]['delta_t'])) 
print("Dew Point: " + str(d['obs'][0]['dew_point'])) 
print("Feels Like: " + str(d['obs'][0]['feels_like'])) 
print("Heat Index: " + str(d['obs'][0]['heat_index'])) 
print("Lightning Strike Count: " + str(d['obs'][0]['lightning_strike_count'])) 
print("Lightning Strike Count Last 1H: " + str(d['obs'][0]['lightning_strike_count_last_1hr'])) 
print("Lightning Strike Count Last 3H: " + str(d['obs'][0]['lightning_strike_count_last_3hr'])) 
print("Lightning Strike Last Distance: " + str(d['obs'][0]['lightning_strike_last_distance'])) 
print("Lightning Strike Last Epoch: " + str(d['obs'][0]['lightning_strike_last_epoch'])) 
print("Precip: " + str(d['obs'][0]['precip'])) 
print("Precip Accum Last 1H: " + str(d['obs'][0]['precip_accum_last_1hr'])) 
print("Precip Accum Local Day: " + str(d['obs'][0]['precip_accum_local_day'])) 
print("Precip Accum Local Day Final: " + str(d['obs'][0]['precip_accum_local_day_final'])) 
print("Precip Accum Local Yesterday: " + str(d['obs'][0]['precip_accum_local_yesterday'])) 
print("Precip Accum Local Yesterday: Final: " + str(d['obs'][0]['precip_accum_local_yesterday_final'])) 
print("Precip Analysis Type Yesterday: " + str(d['obs'][0]['precip_analysis_type_yesterday'])) 
print("Precip Minutes Local Day: " + str(d['obs'][0]['precip_minutes_local_day'])) 
print("Prceip Minutes Local Yesterday: " + str(d['obs'][0]['precip_minutes_local_yesterday'])) 
print("Precip Minutes Local Yesterday Final: " + str(d['obs'][0]['precip_minutes_local_yesterday_final'])) 
print("Pressure Trend: " + str(d['obs'][0]['pressure_trend'])) 
print("Relative Humidity: " + str(d['obs'][0]['relative_humidity'])) 
print("Sea Level Pressure: " + str(d['obs'][0]['sea_level_pressure'])) 
print("Solar Radiation: " + str(d['obs'][0]['solar_radiation'])) 
print("Station Pressure: " + str(d['obs'][0]['station_pressure'])) 
print("Timestamp: " + str(d['obs'][0]['timestamp'])) 
print("UV: " + str(d['obs'][0]['uv'])) 
print("Wet Bulb Globe Temperature: " + str(d['obs'][0]['wet_bulb_globe_temperature'])) 
print("Wet Bulb Temperature: " + str(d['obs'][0]['wet_bulb_temperature'])) 
print("Wind Average: " + str(d['obs'][0]['wind_avg'])) 
print("Wind Chill: " + str(d['obs'][0]['wind_chill'])) 
print("Wind Direction: " + str(d['obs'][0]['wind_direction'])) 
print("Wind Gust: " + str(d['obs'][0]['wind_gust'])) 
print("Wind Lull: " + str(d['obs'][0]['wind_lull'])) 
print("Public Name: " + str(d['public_name'])) 
print("Station ID: " + str(d['station_id'])) 
print("Station Name: " + str(d['station_name']))
print("Units Direction: " + str(d['station_units']['units_direction']))
print("Units Distance: " + str(d['station_units']['units_distance']))
print("Units Other: " + str(d['station_units']['units_other']))
print("Units Precip: " + str(d['station_units']['units_precip']))
print("Units Pressure: " + str(d['station_units']['units_pressure']))
print("Units Temp: " + str(d['station_units']['units_temp']))
print("Units Wind: " + str(d['station_units']['units_wind']))
print("Status Code: " + str(d['status']['status_code']))
print("Status Message: " + str(d['status']['status_message']))
print("Time Zone: " + str(d['timezone']))

print("")
print("Getting Stations:")
URL = "https://swd.weatherflow.com/swd/rest/stations?token={}".format(token)
print(URL)
r = requests.get(url = URL)
d = r.json()
print(d)
print("Stations:")
for s in d['stations']:
    print("Created Epoch: " + str(s['created_epoch']))
    print("Is Local Mode: " + str(s['is_local_mode']))
    print("Last Modified Epoch: " + str(s['last_modified_epoch']))
    print("Latitude: " + str(s['latitude']))
    print("Longitude: " + str(s['longitude']))
    print("Location ID: " + str(s['location_id']))
    print("Name: " + str(s['name']))
    print("Public Name: " + str(s['public_name']))
    print("Station ID: " + str(s['station_id']))
    print("Elevation: " + str(s['station_meta']['elevation']))
    print("Share With WF: " + str(s['station_meta']['share_with_wf']))
    print("Share With WU: " + str(s['station_meta']['share_with_wu']))
    print("Timezone: " + str(s['timezone']))
    print("Timezone Offset Minutes: " + str(s['timezone_offset_minutes']))
    print("Station Items:")
    for i in d['stations'][0]['station_items']:
        print("   Device ID: " + str(i['device_id']))
        print("   Item: " + str(i['item']))
        print("   Location ID: " + str(i['location_id']))
        print("   Locatioin Item ID: " + str(i['location_item_id']))
        try:
            print("   Sort :" + str(i['sort']))
        except KeyError:
            pass
        print("   Station ID: " + str(i['station_id']))
        print("   Station Item ID: " + str(i['station_item_id']))
        print("*****")
    print("Devices:")
    for s in d['stations'][0]['devices']:
        print("   Device ID: " + str(s['device_id']))
        print("   Device AGL: " + str(s['device_meta']['agl']))
        print("   Environment: " + str(s['device_meta']['environment']))
        print("   Name: " + str(s['device_meta']['name']))
        print("   Wifi Network Name" + str(s['device_meta']['wifi_network_name']))
        print("   Device Type: " + str(s['device_type']))
        print("   Firmware Revision: " + str(s['firmware_revision']))
        print("   Hardware Revision: " + str(s['hardware_revision']))
        print("   Location ID: " + str(s['location_id']))
        print("   Serial Number: " + str(s['serial_number']))
        try:
            print("   Show Precip Final: " + str(s['device_settings']['show_precip_final']))
        except KeyError:
            pass
        print("*****")
print("Status Code: " + str(d['status']['status_code']))
print("Status Message: " + str(d['status']['status_message']))

